### ISSUE TITLE
type change error

### ISSUE THREAD

**Issue by itsatan** [jianxiaoBai/react-json-editor-ui#12]
示例：https://jianxiaobai.github.io/react-json-editor-ui/
复现步骤：
1. name 修改类型为 boolean
2. others -> id 修改类型为 boolean
3. others -> id 修改类型为 string
此时 name 的类型会随着 others -> id 的类型而变化

**Comment by jianxiaoBai** [comment]
感谢提出，现已在 1.0.8 版本修复。
