### ISSUE TITLE
Dropdown hides to behind when opened up in a modal

### ISSUE THREAD

**Issue by HenryHengZJ** [jianxiaoBai/react-json-editor-ui#13]
When using JSONEditor in a modal, the dropdown appears to hide behind the modal as shown:

<img width="499" alt="image" src="https://github.com/jianxiaoBai/react-json-editor-ui/assets/26460777/e70405ee-9b85-49a0-890e-dd4a6116523d">

**Comment by ejbriones** [comment]
Hello,

same issue using React MUI v4 Dialog.
![image](https://github.com/jianxiaoBai/react-json-editor-ui/assets/16726786/41e828df-e222-463f-963c-e139852dec7e)

**Comment by jianxiaoBai** [comment]
![image](https://github.com/jianxiaoBai/react-json-editor-ui/assets/20953838/4f29578f-7a92-4e61-bf93-28af607ade88)

The .ant-select-dropdown z-index value is 1050, make sure your pop-up has a z-index greater than 1050, or you can set the .ant-select-dropdown z-index separately.

@ejbriones @HenryHengZJ
