### ISSUE TITLE
Changing keys in version 1.0.8 doesn't work

### ISSUE THREAD

**Issue by fr3fou** [jianxiaoBai/react-json-editor-ui#15]
It seems that when changing the key name the object gets recursively duplicated under the previous key

https://github.com/jianxiaoBai/react-json-editor-ui/assets/1344906/b336fbb5-8522-44fc-ad5b-c8370bfff200

Version 1.0.7 doesn't have this issue

**Comment by jianxiaoBai** [comment]
I've fixed this in v1.0.9 and thank you very much for your feedback! 🤝
