### ISSUE TITLE
Incorrect boolean values in editor

### ISSUE THREAD

**Issue by LeroViten** [jianxiaoBai/react-json-editor-ui#2]
Sometimes editor shows incorrect boolean values. As in screenshot below the right part shows stringified object that is passed to editor and the boolean value here is correct. But the left part (editor) shows incorrectly.
![Screenshot from 2023-04-12 10-40-12](https://user-images.githubusercontent.com/3999696/231388461-0670fa60-5ea8-43c9-8cbe-859d3df4df5b.png)

**Comment by jianxiaoBai** [comment]
Thank you feedback on this question, I had been fixed it in the 1.0.7 version, please upgrade it. @LeroViten
